services:
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - inventreedatabase:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: inventree
      POSTGRES_USER: inventree_user
      POSTGRES_PASSWORD: inventree_password

  redis:
    image: redis:7.0
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  inventreedatabase:
